### ISSUE TITLE
about centroid

### ISSUE THREAD

**Issue by zmokokokok** [ex2tron/OpenCV-Python-Tutorial#4]
Sir, could you please tell me how to display the centroid on the image? Thank you!

**Comment by ex2tron** [comment]
Display or calculate?
if you want to display the centroid value on the image, just use the drawing function (cv2.putText()).
[Drawing](http://ex2tron.wang/opencv-python-drawing-function/#%E6%B7%BB%E5%8A%A0%E6%96%87%E5%AD%97)

For calculation, you can use moments.
[Image moments](http://ex2tron.wang/opencv-python-contour-features/#%E5%9B%BE%E5%83%8F%E7%9F%A9)

**Comment by zmokokokok** [comment]
Thank you sir, that's really helpful.
